import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import Footer from "@/Components/Footer/Footer";
import { paragraphFont } from "@/lib/Font";

export const metadata = {
  title: "Sazzad | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`scroll-mx-0 ${paragraphFont.className} `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
